spring.application.name=solarchargecalculator
spring.config.import=optional:file:.env[.properties]

server.tomcat.accesslog.enabled=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_UserName}
spring.datasource.password=${DB_Pwd}